version: '3.8'
services:
  server:
    container_name: server
    image: node:16-alpine
    working_dir: /app
    volumes:
      - $PWD/server:/app
    command: sh -c "npm install -f && node index.js"
  client:
    container_name: client
    image: node:16-alpine
    working_dir: /app
    volumes:
      - $PWD/client:/app
    environment:
      - BASE_URL=server
    command: sh -c 'npm install -f && sleep 4 && node index.js'
    depends_on:
      - server
